apiVersion: v1
kind: Service
metadata:
  labels:
    app: acme-service
    deployment: acme-predictive-stocks
  name: acme-service
spec:
  ports:
  - port: 8080
    name: home-page
  selector:
    app: acme-portal
  type: LoadBalancer
